title: sasurahime
description: macOS developer cache cleaner written in Rust
url: https://armaniacs.github.io/sasurahime
github_repo: https://github.com/armaniacs/sasurahime

theme: jekyll-theme-cayman
